### ISSUE TITLE
Proxy option on Skype connection

### ISSUE THREAD

**Issue by PlanetWilson** [o365soa/soa#11]
I haven't traced through what happens when you choose -useproxy but I found I couldn't connect to Skype Online with that selected. I had to edit the module to create a session option object just before the New-CsOnlineSession called to tell it to use the IEProxy before it would connect.

e.g.
Line 1242 of SOA-Prerequisites.psm1

```
$so = New-PSSessionOption -ProxyAccessType IEConfig
$SfBOSession = New-CsOnlineSession -OverrideAdminDomain $SfBOAdminDomain -ErrorVariable $ConnectError -ErrorAction:SilentlyContinue -SessionOption $so

```

**Comment by bieberium** [comment]
I had the same problem, but you can re-use the existing variable and just modify line 1241:

`$SfBOSession = New-CsOnlineSession -OverrideAdminDomain $SfBOAdminDomain -ErrorVariable $ConnectError -ErrorAction:SilentlyContinue **-SessionOption $RPSProxySetting**`

**Comment by bieberium** [comment]
As an FYI: The SOA Engagement / Data collection script has the same issue and needs the SessionOption parameter set.

**Comment by o365soa** [comment]
Thanks, the code change has been merged in Git now and will be pushed to the PS Module during the next SOA release cycle. I will make similar changes to the data collection script. Thanks for your assistance.
