### ISSUE TITLE
Fix for WARNING: Unable to resolve package source 'https://www.powershellgallery.com/api/v2'

### ISSUE THREAD

**Issue by michaelblumenthal** [o365soa/soa#5]
If you get the warning 
WARNING: Unable to resolve package source 'https://www.powershellgallery.com/api/v2'.
the fix is to run this PowerShell command before you run "install-module SOA":

[Net.ServicePointManager]::SecurityProtocol=[Net.SecurityProtocolType]::Tls12

**Comment by cammurray** [comment]
Hi @michaelblumenthal 

Are you referring to this: https://devblogs.microsoft.com/powershell/powershell-gallery-tls-support/

?

**Comment by michaelblumenthal** [comment]
Yes.
Linking to that page from the SOA page would help people resolve that error.

Michael Blumenthal, Microsoft MVP – Office 365

Blog: https://MichaelBlumenthal.me
LinkedIn: http://bit.ly/MBB-LI
Email: Michael@MichaelBlumenthal.me  / m@BlumenthalIT.com
Meetup: Office 365 Adoption User Group (Chicagoland Chapter)


________________________________

**Comment by miss-tech** [comment]
Hi @michaelblumenthal,

We've now added some code changes and readme changes to resolve this issue. Thanks for submitting 👍 

Emily
