### ISSUE TITLE
MS Graph authentication fails with error AADSTS50105

### ISSUE THREAD

**Issue by GoliatMB** [o365soa/soa#90]
Hi, In some cases MS Graph authentication fails with error AADSTS50105. To resolve this, you must configure the Microsoft Graph Command Line Tools API to disable "Assignment Required" or assign the application explicitly to the user. In my case, I have explicitly assigned my user to the application. I don't know if it would also be good to indicate it in the "Important" text. Thank team,

**Comment by sbueffel** [comment]
Assignment required is not enabled by default, but if it is enabled, yes, the user must be assigned the application directly or a member of a group that is assigned the application. This applies not only to the PS Graph SDK, but any module used in the assessment, if the tenant has configured a module to require assignment.
